AllCops:
  TargetRubyVersion: '2.5'
  AllowSymlinksInCacheRootDirectory: true
  NewCops: enable
  Exclude:
    - lib/melt/*.tab.rb
    - tmp/**/*.rb
    - vendor/bundle/**/*

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Exclude:
    - features/support/env.rb
    - spec/**/*.rb

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
