AllCops:
  TargetRubyVersion: '2.5'
  AllowSymlinksInCacheRootDirectory: true
  NewCops: enable
  Exclude:
    - lib/puffy/*.tab.rb
    - tmp/**/*.rb
    - vendor/bundle/**/*

plugins:
  - rubocop-rake
  - rubocop-rspec

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - puffy.gemspec
    - spec/**/*.rb

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Exclude:
    - spec/**/*.rb

RSpec/ExampleLength:
  Max: 50

RSpec/MultipleExpectations:
  Max: 10

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/core_ext_spec.rb

Style/Documentation:
  Exclude:
    - features/support/env.rb
    - spec/**/*.rb

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
